import OfferCard from '@/Components/OfferCard';
import StudentLayout from '@/Layouts/StudentLayout';
import { Head, Link } from '@inertiajs/react';

type Offer = { id: number; programName: string; priceCents: number; expiresAt?: string | null; courseCount: number };

export default function Index({ offers }: { offers: Offer[] }) {
    return <StudentLayout><Head title="Disponível para você" />
        <section className="relative isolate overflow-hidden rounded-[1.35rem] border border-white/[0.1] bg-[#131018] px-6 py-10 sm:px-10 sm:py-14 lg:px-14"><div aria-hidden className="absolute inset-y-0 right-0 hidden w-1/2 bg-[radial-gradient(circle_at_75%_30%,rgba(152,71,221,.24),transparent_10%),radial-gradient(ellipse_at_80%_50%,rgba(86,37,142,.35),transparent_45%)] lg:block" /><div className="relative max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Seleção ASEX</p><h1 className="mt-4 text-4xl font-black tracking-[-0.06em] text-white sm:text-6xl">O que vem a seguir é seu.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/65 sm:text-lg">Programas escolhidos para ampliar a sua prática, liderança e resultado.</p></div></section>
        {offers.length ? <section className="mt-14 sm:mt-20"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Para você</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl">Programas disponíveis</h2></div><p className="hidden text-sm text-white/50 sm:block">Acesso liberado após a confirmação do pagamento.</p></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} />)}</div></section> : <section className="mt-14 max-w-2xl rounded-[1.35rem] border border-dashed border-white/15 bg-white/[0.025] px-6 py-14 text-center sm:mt-20 sm:px-10"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Em breve</p><h2 className="mt-3 text-3xl font-black tracking-[-0.04em] text-white">Nenhuma oferta disponível agora.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-white/60 sm:text-base">Quando houver um programa preparado para você, ele aparecerá aqui.</p><Link className="asex-gradient mt-8 inline-flex min-h-12 items-center justify-center rounded-lg px-6 py-3 text-sm font-bold text-white transition hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-[#09070d]" href="/my-courses">Ir para meus cursos</Link></section>}
    </StudentLayout>;
}
