import ProgressBar from '@/Components/ProgressBar';
import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';

type Lesson = { id: number; title: string; durationSeconds?: number | null; isPreview: boolean; completed: boolean; };
type Props = { course: { title: string; description?: string | null; progress: number; modules: Array<{ id: number; title: string; position: number; lessons: Lesson[]; }>; }; };

const duration = (seconds?: number | null) => seconds ? `${Math.ceil(seconds / 60)} min` : 'Aula';

export default function Show({ course }: Props) {
    return <AppLayout><Head title={course.title} /><div className="grid gap-10 lg:grid-cols-[1fr_20rem]"><section><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Curso</p><h1 className="mt-2 text-4xl font-black tracking-tight text-slate-950">{course.title}</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">{course.description}</p><div className="mt-8 max-w-xl rounded-2xl border border-indigo-100 bg-white p-6"><ProgressBar value={course.progress} label="Progresso do curso" /></div><div className="mt-10 space-y-4">{course.modules.map((module) => <section key={module.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-4"><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Módulo {module.position}</p><h2 className="mt-1 text-lg font-bold text-slate-900">{module.title}</h2></div><ul>{module.lessons.map((lesson) => <li key={lesson.id} className="flex items-center justify-between gap-4 border-b border-slate-100 px-6 py-4 last:border-0"><Link className="flex min-w-0 items-center gap-3 font-medium text-slate-800 hover:text-indigo-700" href={`/lessons/${lesson.id}`}><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${lesson.completed ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{lesson.completed ? '✓' : '▶'}</span><span className="truncate">{lesson.title}</span></Link><span className="shrink-0 text-sm text-slate-500">{duration(lesson.durationSeconds)}</span></li>)}</ul></section>)}</div></section><aside className="h-fit rounded-2xl bg-slate-950 p-6 text-white lg:sticky lg:top-8"><p className="text-sm font-semibold text-indigo-300">Seu próximo passo</p><p className="mt-2 text-xl font-bold">Retome sua trilha quando quiser.</p><p className="mt-3 text-sm leading-6 text-slate-300">As aulas concluídas ficam registradas automaticamente na sua conta.</p></aside></div></AppLayout>;
}
