import ProgressBar from '@/Components/ProgressBar';
import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';

type Lesson = { id: number; title: string; durationSeconds?: number | null; isPreview: boolean; completed: boolean; };
type Props = { course: { title: string; description?: string | null; progress: number; nextLessonId?: number | null; instructor?: string | null; durationMinutes?: number; modules: Array<{ id: number; title: string; position: number; lessons: Lesson[]; }>; }; };

const duration = (seconds?: number | null) => seconds ? `${Math.ceil(seconds / 60)} min` : 'Aula';

export default function Show({ course }: Props) {
    return <AppLayout><Head title={course.title} /><div className="grid gap-10 lg:grid-cols-[1fr_20rem]"><section><p className="eyebrow text-brand-700">Curso</p><h1 className="mt-2 text-4xl font-black tracking-tight">{course.title}</h1><p className="mt-4 max-w-2xl text-lg text-ink/65">{course.description}</p><p className="mt-4 text-sm text-ink/55">{course.instructor && `Instrutor: ${course.instructor}`} {course.instructor && course.durationMinutes ? '·' : ''} {course.durationMinutes ? `${course.durationMinutes} min` : ''}</p><div className="mt-8 max-w-xl rounded-2xl border border-brand-100 bg-white p-6"><ProgressBar value={course.progress} label="Progresso do curso" /></div><div className="mt-10 space-y-4">{course.modules.length ? course.modules.map((module) => <section key={module.id} className="overflow-hidden rounded-2xl border border-ink/10 bg-white"><div className="border-b border-ink/10 px-6 py-4"><p className="eyebrow text-brand-700">Módulo {module.position}</p><h2 className="mt-1 text-lg font-bold">{module.title}</h2></div><ul>{module.lessons.map((lesson) => <li key={lesson.id} className="flex items-center justify-between gap-4 border-b border-ink/10 px-6 py-4 last:border-0"><Link className="flex min-w-0 items-center gap-3 font-medium hover:text-brand-700" href={`/lessons/${lesson.id}`}><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${lesson.completed ? 'bg-brand-100 text-brand-700' : 'bg-sand text-ink/55'}`}>{lesson.completed ? '✓' : '▶'}</span><span className="truncate">{lesson.title}</span></Link><span className="shrink-0 text-sm text-ink/55">{duration(lesson.durationSeconds)}</span></li>)}</ul></section>) : <div className="rounded-2xl border border-dashed border-ink/20 bg-white p-8 text-center text-sm leading-6 text-ink/60">Este curso ainda não possui aulas disponíveis.</div>}</div></section><aside className="h-fit rounded-2xl bg-ink p-6 text-white lg:sticky lg:top-8"><p className="eyebrow text-brand-300">Seu próximo passo</p><p className="mt-2 text-xl font-bold">Retome sua trilha quando quiser.</p><p className="mt-3 text-sm leading-6 text-white/65">As aulas concluídas ficam registradas na sua conta.</p>{course.nextLessonId && <Link href={`/lessons/${course.nextLessonId}`} className="mt-6 inline-block rounded-lg bg-brand-400 px-4 py-2.5 text-sm font-bold text-ink">{course.progress > 0 ? 'Continuar curso' : 'Começar curso'}</Link>}</aside></div></AppLayout>;
}
