import CourseCover from '@/Components/CourseCover';
import LessonRow from '@/Components/LessonRow';
import ProgressBar from '@/Components/ProgressBar';
import StudentLayout from '@/Layouts/StudentLayout';
import { Head, Link } from '@inertiajs/react';

type Lesson = { id: number; title: string; durationSeconds?: number | null; videoId?: string | null; isPreview: boolean; completed: boolean; };
type Props = { course: { title: string; slug: string; description?: string | null; thumbnailPath?: string | null; videoId?: string | null; progress: number; nextLessonId?: number | null; instructor?: string | null; category?: string | null; level?: string | null; lessonCount: number; moduleCount: number; modules: Array<{ id: number; title: string; position: number; completedLessons: number; lessons: Lesson[]; }>; }; };

export default function Show({ course }: Props) {
    const durationMinutes = Math.ceil(course.modules.flatMap((module) => module.lessons).reduce((seconds, lesson) => seconds + (lesson.durationSeconds ?? 0), 0) / 60);
    const metadata = [course.instructor && `Com ${course.instructor}`, course.category, course.level, `${course.lessonCount} aulas`, durationMinutes > 0 && `${durationMinutes} min`].filter((item): item is string => typeof item === 'string');

    return <StudentLayout><Head title={course.title} />
        <section className="relative isolate min-h-[470px] overflow-hidden rounded-2xl border border-white/[0.08] bg-[#15101b] px-6 py-9 sm:px-10 sm:py-12 lg:flex lg:items-end lg:px-14 lg:py-14"><div className="absolute inset-y-0 right-0 w-full overflow-hidden opacity-60 lg:w-[60%]"><CourseCover className="h-full w-full" thumbnailPath={course.thumbnailPath} title={course.title} videoId={course.videoId} /><div aria-hidden className="absolute inset-0 bg-[linear-gradient(90deg,#15101b_5%,#15101b_35%,rgba(21,16,27,0.18)_100%)]" /></div><span aria-hidden className="absolute right-10 top-0 h-80 w-80 rotate-45 border border-[#9347dd]/35" />
            <div className="relative z-10 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Curso</p><h1 className="mt-4 text-4xl font-black tracking-[-0.05em] text-white sm:text-5xl">{course.title}</h1>{course.description && <p className="mt-5 max-w-xl text-base leading-7 text-white/70 sm:text-lg">{course.description}</p>}<div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-sm font-medium text-white/65">{metadata.map((item) => <span key={item}>{item}</span>)}</div><div className="mt-8 max-w-sm"><ProgressBar label="Seu progresso" tone="dark" value={course.progress} /></div>{course.nextLessonId && <Link className="asex-gradient mt-8 inline-flex min-h-12 items-center rounded-lg px-6 py-3 text-sm font-bold text-white transition hover:brightness-110" href={`/lessons/${course.nextLessonId}`}>{course.progress === 100 ? 'Revisar curso' : course.progress > 0 ? 'Continuar curso' : 'Começar curso'} <span aria-hidden className="ml-2">→</span></Link>}</div>
        </section>
        <section className="mt-12 sm:mt-16"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Conteúdo do curso</p><h2 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-4xl">Seu caminho de aprendizagem</h2><p className="mt-3 text-sm leading-6 text-white/55 sm:text-base">Avance aula a aula e acompanhe o seu progresso em cada módulo.</p></div><div className="mt-8 space-y-4">{course.modules.length ? course.modules.map((module) => <section className="overflow-hidden border border-white/[0.1] bg-[#15101b]" key={module.id}><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[0.08] px-5 py-5 sm:px-7"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Módulo {String(module.position).padStart(2, '0')}</p><h3 className="mt-2 text-xl font-black text-white">{module.title}</h3></div><p className="text-sm font-medium text-white/55">{module.completedLessons} de {module.lessons.length} aulas</p></div><div className="divide-y divide-white/[0.06]">{module.lessons.map((lesson, index) => <LessonRow completed={lesson.completed} current={lesson.id === course.nextLessonId} durationSeconds={lesson.durationSeconds} id={lesson.id} key={lesson.id} number={index + 1} title={lesson.title} videoId={lesson.videoId} />)}</div></section>) : <div className="border border-dashed border-white/15 px-6 py-14 text-center text-sm text-white/55">Este curso ainda não possui aulas disponíveis.</div>}</div></section>
    </StudentLayout>;
}
