import VideoPlayer from '@/Components/VideoPlayer';
import AppLayout from '@/Layouts/AppLayout';
import { Head, Link, router } from '@inertiajs/react';

type Props = { lesson: { id: number; title: string; description?: string | null; videoProvider: 'youtube' | 'panda'; videoId?: string | null; videoUrl?: string | null; completed: boolean; }; course: { title: string; slug: string; modules: Array<{ id: number; title: string; lessons: Array<{ id: number; title: string; completed: boolean; }>; }>; }; };

export default function Show({ lesson, course }: Props) {
    const markComplete = () => router.put(`/lessons/${lesson.id}/progress`, { completed: !lesson.completed });
    return <AppLayout><Head title={lesson.title} /><div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_22rem]"><section><VideoPlayer provider={lesson.videoProvider} videoId={lesson.videoId} videoUrl={lesson.videoUrl} title={lesson.title} /><div className="mt-7 flex flex-wrap items-start justify-between gap-4"><div><Link href={`/courses/${course.slug}`} className="text-sm font-semibold text-indigo-700 hover:text-indigo-900">{course.title}</Link><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">{lesson.title}</h1></div><button type="button" onClick={markComplete} className={`rounded-lg px-4 py-2.5 text-sm font-bold ${lesson.completed ? 'bg-emerald-100 text-emerald-800' : 'bg-indigo-700 text-white hover:bg-indigo-800'}`}>{lesson.completed ? '✓ Aula concluída' : 'Marcar como concluída'}</button></div><p className="mt-5 max-w-3xl whitespace-pre-line text-slate-600">{lesson.description}</p></section><aside className="overflow-hidden rounded-2xl border border-slate-200 bg-white xl:sticky xl:top-8 xl:h-[calc(100vh-8rem)]"><div className="border-b border-slate-100 px-5 py-4"><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Conteúdo do curso</p><h2 className="mt-1 font-bold text-slate-900">{course.title}</h2></div><div className="max-h-[60vh] overflow-y-auto p-3 xl:max-h-[calc(100vh-14rem)]">{course.modules.map((module) => <section key={module.id} className="mb-4"><h3 className="px-2 py-2 text-sm font-bold text-slate-700">{module.title}</h3>{module.lessons.map((courseLesson) => <Link key={courseLesson.id} href={`/lessons/${courseLesson.id}`} className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${courseLesson.id === lesson.id ? 'bg-indigo-50 font-bold text-indigo-800' : 'text-slate-600 hover:bg-slate-50'}`}><span>{courseLesson.completed ? '✓' : courseLesson.id === lesson.id ? '▶' : '○'}</span><span>{courseLesson.title}</span></Link>)}</section>)}</div></aside></div></AppLayout>;
}
