import LessonRow from '@/Components/LessonRow';
import ProgressBar from '@/Components/ProgressBar';
import VideoPlayer from '@/Components/VideoPlayer';
import StudentLayout from '@/Layouts/StudentLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';

type Lesson = { id: number; title: string; description?: string | null; videoProvider: 'youtube' | 'panda'; videoId?: string | null; videoUrl?: string | null; completed: boolean; number: number; };
type CourseLesson = { id: number; title: string; number: number; completed: boolean; videoId?: string | null; durationSeconds?: number | null };
type Props = { lesson: Lesson; course: { slug: string; title: string; instructor?: string | null; category?: string | null; level?: string | null; progress: { completedLessons: number; totalLessons: number; percentage: number }; modules: { id: number; title: string; position: number; lessons: CourseLesson[] }[]; }; navigation: { previousLessonId?: number | null; nextLessonId?: number | null }; };
const lessonNumber = (number: number) => String(number).padStart(2, '0');

export default function Show({ lesson, course, navigation }: Props) {
    const [completed, setCompleted] = useState(lesson.completed);
    const [processing, setProcessing] = useState(false);
    const [feedbackError, setFeedbackError] = useState<string | null>(null);
    const completedLessons = course.progress.completedLessons + (completed === lesson.completed ? 0 : completed ? 1 : -1);
    const courseCompleted = course.progress.totalLessons > 0 && completedLessons === course.progress.totalLessons;
    const progressPercentage = course.progress.totalLessons > 0 ? Math.round((completedLessons / course.progress.totalLessons) * 100) : 0;
    const update = (nextCompleted: boolean, nextLessonId?: number | null) => { const previous = completed; setCompleted(nextCompleted); setFeedbackError(null); router.put(`/lessons/${lesson.id}/progress`, { completed: nextCompleted }, { preserveScroll: true, onStart: () => setProcessing(true), onError: () => { setCompleted(previous); setFeedbackError('Não foi possível atualizar o progresso. Tente novamente.'); }, onSuccess: () => { if (nextLessonId) router.visit(`/lessons/${nextLessonId}`); }, onFinish: () => setProcessing(false) }); };

    return <StudentLayout><Head title={lesson.title} />
        <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_23rem] xl:items-start xl:gap-10"><section className="min-w-0"><Link className="mb-5 inline-flex text-sm font-semibold text-[#c28aff] transition hover:text-white" href={`/courses/${course.slug}`}>← {course.title}</Link><VideoPlayer provider={lesson.videoProvider} title={lesson.title} videoId={lesson.videoId} videoUrl={lesson.videoUrl} />
            <div className="border-b border-white/[0.1] py-7"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Aula {lessonNumber(lesson.number)}</p><h1 className="mt-3 text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl">{lesson.title}</h1>{lesson.description && <p className="mt-4 max-w-3xl whitespace-pre-line text-base leading-7 text-white/65">{lesson.description}</p>}</div>
            <div className="mt-6 flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-white">Acompanhamento da aula</p><p className="mt-1 text-sm text-white/50">Marque quando concluir para atualizar seu progresso.</p></div><button className={`inline-flex min-h-12 items-center justify-center rounded-lg px-5 py-3 text-sm font-bold transition disabled:cursor-not-allowed disabled:opacity-50 ${completed ? 'bg-white/[0.1] text-[#d5b0ff] hover:bg-white/[0.15]' : 'asex-gradient text-white hover:brightness-110'}`} disabled={processing} onClick={() => update(!completed)} type="button">{processing ? 'Salvando…' : completed ? '✓ Aula concluída' : 'Marcar como concluída'}</button></div>
            {feedbackError && <p className="mt-4 border border-rose-400/30 bg-rose-500/10 px-4 py-3 text-sm font-semibold text-rose-200" role="alert">{feedbackError}</p>}{courseCompleted && <div className="mt-7 border border-[#9347dd]/35 bg-[#2b0870]/35 p-6"><p className="text-lg font-black text-white">Curso concluído</p><p className="mt-2 text-sm leading-6 text-white/65">Você concluiu todas as aulas de {course.title}.</p></div>}
            <nav aria-label="Navegação entre aulas" className="mt-8 flex flex-col gap-3 border-t border-white/[0.1] pt-6 sm:flex-row sm:items-center sm:justify-between">{navigation.previousLessonId ? <Link className="inline-flex min-h-12 items-center justify-center rounded-lg border border-white/[0.15] px-5 py-3 text-sm font-bold text-white transition hover:bg-white/[0.06]" href={`/lessons/${navigation.previousLessonId}`}>← Aula anterior</Link> : <span />}{navigation.nextLessonId ? <button className="asex-gradient inline-flex min-h-12 items-center justify-center rounded-lg px-5 py-3 text-sm font-bold text-white transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50" disabled={processing} onClick={() => update(true, navigation.nextLessonId)} type="button">Próxima aula →</button> : <p className="px-4 py-3 text-center text-sm font-semibold text-white/55">{courseCompleted ? 'Você chegou ao final deste curso.' : 'Esta é a última aula do curso.'}</p>}</nav>
        </section>
        <aside className="overflow-hidden border border-white/[0.1] bg-[#15101b] xl:sticky xl:top-6 xl:max-h-[calc(100vh-3rem)]"><div className="border-b border-white/[0.1] px-5 py-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Conteúdo do curso</p><h2 className="mt-2 text-xl font-black text-white">{course.title}</h2>{(course.instructor || course.category || course.level) && <p className="mt-2 text-sm text-white/50">{[course.instructor, course.category, course.level].filter(Boolean).join(' · ')}</p>}</div><div className="border-b border-white/[0.1] px-5 py-5"><p className="mb-3 text-sm font-bold text-white">Seu progresso</p><p className="mb-3 text-sm text-white/50">{completedLessons} de {course.progress.totalLessons} aulas concluídas</p><ProgressBar label="Progresso" tone="dark" value={progressPercentage} /></div><div className="max-h-80 overflow-y-auto py-2 xl:max-h-[calc(100vh-18rem)]">{course.modules.length ? course.modules.map((module) => <section className="mb-3 last:mb-0" key={module.id}><div className="px-5 py-3"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#c28aff]">Módulo {lessonNumber(module.position)}</p><h3 className="mt-1 text-sm font-black text-white">{module.title}</h3></div><div className="divide-y divide-white/[0.06]">{module.lessons.map((courseLesson) => <LessonRow compact completed={courseLesson.id === lesson.id ? completed : courseLesson.completed} current={courseLesson.id === lesson.id} durationSeconds={courseLesson.durationSeconds} id={courseLesson.id} key={courseLesson.id} number={courseLesson.number} title={courseLesson.title} videoId={courseLesson.videoId} />)}</div></section>) : <p className="px-5 py-8 text-center text-sm leading-6 text-white/55">Este curso ainda não possui aulas disponíveis.</p>}</div></aside></div>
    </StudentLayout>;
}
