import DangerButton from '@/Components/DangerButton';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import Modal from '@/Components/Modal';
import SecondaryButton from '@/Components/SecondaryButton';
import TextInput from '@/Components/TextInput';
import { useForm } from '@inertiajs/react';
import { FormEventHandler, useRef, useState } from 'react';

export default function DeleteUserForm({ className = '', variant = 'default' }: { className?: string; variant?: 'default' | 'student' }) {
    const [confirmingUserDeletion, setConfirmingUserDeletion] = useState(false);
    const passwordInput = useRef<HTMLInputElement>(null);
    const { data, setData, delete: destroy, processing, reset, errors, clearErrors } = useForm({ password: '' });
    const closeModal = () => { setConfirmingUserDeletion(false); clearErrors(); reset(); };
    const deleteUser: FormEventHandler = (event) => { event.preventDefault(); destroy(route('profile.destroy'), { preserveScroll: true, onSuccess: () => closeModal(), onError: () => passwordInput.current?.focus(), onFinish: () => reset() }); };

    if (variant === 'student') {
        return <section className={`space-y-5 ${className}`}><header><p className="text-xs font-semibold uppercase tracking-[0.15em] text-rose-300">Conta</p><h2 className="mt-2 text-xl font-black tracking-tight text-white">Excluir conta</h2><p className="mt-3 text-sm leading-6 text-white/55">Esta ação é permanente e remove os dados da sua conta.</p></header><button className="inline-flex min-h-11 items-center justify-center rounded-lg border border-rose-400/35 px-4 py-2.5 text-sm font-bold text-rose-200 transition hover:bg-rose-500/10" onClick={() => setConfirmingUserDeletion(true)} type="button">Excluir conta</button><Modal onClose={closeModal} show={confirmingUserDeletion} variant="student"><form className="p-6 sm:p-8" onSubmit={deleteUser}><h2 className="text-xl font-black text-white">Excluir sua conta?</h2><p className="mt-3 text-sm leading-6 text-white/65">Esta ação é permanente. Digite sua senha para confirmar a exclusão da conta.</p><div className="mt-6"><label className="grid gap-2 text-sm font-semibold text-white/80" htmlFor="password">Senha<input aria-invalid={Boolean(errors.password)} autoComplete="current-password" className="min-h-12 rounded-lg border border-white/[0.12] bg-[#0e0b14] px-4 text-white focus:border-[#9347dd] focus:ring-[#9347dd]" id="password" name="password" onChange={(event) => setData('password', event.target.value)} ref={passwordInput} type="password" value={data.password} /></label><InputError className="mt-2 text-rose-300" message={errors.password} /></div><div className="mt-7 flex flex-wrap justify-end gap-3"><button className="inline-flex min-h-11 items-center rounded-lg border border-white/[0.15] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-white/[0.06]" onClick={closeModal} type="button">Cancelar</button><button className="inline-flex min-h-11 items-center rounded-lg bg-rose-600 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-rose-500 disabled:cursor-not-allowed disabled:opacity-50" disabled={processing} type="submit">Excluir conta</button></div></form></Modal></section>;
    }

    return <section className={`space-y-6 ${className}`}><header><h2 className="text-lg font-medium text-gray-900">Delete Account</h2><p className="mt-1 text-sm text-gray-600">Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.</p></header><DangerButton onClick={() => setConfirmingUserDeletion(true)}>Delete Account</DangerButton><Modal onClose={closeModal} show={confirmingUserDeletion}><form className="p-6" onSubmit={deleteUser}><h2 className="text-lg font-medium text-gray-900">Are you sure you want to delete your account?</h2><p className="mt-1 text-sm text-gray-600">Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.</p><div className="mt-6"><InputLabel className="sr-only" htmlFor="password" value="Password" /><TextInput className="mt-1 block w-3/4" id="password" isFocused name="password" onChange={(event) => setData('password', event.target.value)} placeholder="Password" ref={passwordInput} type="password" value={data.password} /><InputError className="mt-2" message={errors.password} /></div><div className="mt-6 flex justify-end"><SecondaryButton onClick={closeModal}>Cancel</SecondaryButton><DangerButton className="ms-3" disabled={processing}>Delete Account</DangerButton></div></form></Modal></section>;
}
