import InputError from '@/Components/InputError';
import PrimaryButton from '@/Components/PrimaryButton';
import { PageProps } from '@/types';
import { useForm, usePage } from '@inertiajs/react';
import { FormEvent } from 'react';

type Props = { mustVerifyEmail: boolean; status?: string; className?: string; variant?: 'default' | 'student' };

export default function UpdateProfileInformation({ className = '', variant = 'default' }: Props) {
    const user = usePage<PageProps>().props.auth.user;
    const form = useForm({ name: user.name, email: user.email, phone: user.phone ?? '', job_title: user.job_title ?? '', company: user.company ?? '', business_segment: user.business_segment ?? '', city: user.city ?? '', state: user.state ?? '' });
    const submit = (event: FormEvent) => { event.preventDefault(); form.patch(route('profile.update')); };
    const studentField = (key: keyof typeof form.data, label: string, type = 'text', autoComplete?: string) => <label className="grid gap-2 text-sm font-semibold text-white/80" htmlFor={key}>{label}<input aria-invalid={Boolean(form.errors[key])} autoComplete={autoComplete} className="min-h-12 rounded-lg border border-white/[0.12] bg-[#0e0b14] px-4 text-white placeholder:text-white/30 focus:border-[#9347dd] focus:ring-[#9347dd]" id={key} onChange={(event) => form.setData(key, event.target.value)} type={type} value={form.data[key]} /><InputError className="text-rose-300" message={form.errors[key]} /></label>;

    if (variant === 'student') {
        return <section className={className}><header><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Informações pessoais</p><h2 className="mt-2 text-2xl font-black tracking-tight text-white">Seus dados</h2><p className="mt-3 text-sm leading-6 text-white/55">Mantenha suas informações atualizadas para uma experiência mais relevante.</p></header><form className="mt-7 space-y-8" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2">{studentField('name', 'Nome completo', 'text', 'name')}{studentField('email', 'E-mail', 'email', 'email')}{studentField('phone', 'Telefone', 'tel', 'tel')}</div><div className="border-t border-white/[0.08] pt-8"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c28aff]">Informações profissionais</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{studentField('job_title', 'Cargo ou função', 'text', 'organization-title')}{studentField('company', 'Empresa', 'text', 'organization')}{studentField('business_segment', 'Segmento do estabelecimento')}{studentField('city', 'Cidade', 'text', 'address-level2')}{studentField('state', 'Estado (UF)', 'text', 'address-level1')}</div></div><div className="flex flex-wrap items-center gap-4"><button className="asex-gradient inline-flex min-h-12 items-center justify-center rounded-lg px-5 py-3 text-sm font-bold text-white transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50" disabled={form.processing} type="submit">Salvar alterações</button>{form.recentlySuccessful && <span aria-live="polite" className="text-sm font-semibold text-[#d8bdff]">Perfil atualizado com sucesso.</span>}</div></form></section>;
    }

    const field = (key: keyof typeof form.data, label: string, type = 'text') => <label className="grid gap-2 text-sm font-semibold">{label}<input className="rounded-lg border-ink/15" onChange={(event) => form.setData(key, event.target.value)} type={type} value={form.data[key]} /><InputError message={form.errors[key]} /></label>;
    return <section className={className}><header><p className="eyebrow text-brand-700">Meu perfil</p><h2 className="mt-2 text-2xl font-black">Dados profissionais</h2><p className="mt-2 text-sm text-ink/65">Complete seus dados para personalizar sua experiência.</p></header><form className="mt-7 grid gap-5 sm:grid-cols-2" onSubmit={submit}>{field('name', 'Nome completo')}{field('email', 'E-mail', 'email')}{field('phone', 'Telefone')}{field('job_title', 'Cargo ou função')}{field('company', 'Empresa')}{field('business_segment', 'Segmento do estabelecimento')}{field('city', 'Cidade')}{field('state', 'Estado (UF)')}<div className="flex items-center gap-4 sm:col-span-2"><PrimaryButton disabled={form.processing}>Salvar alterações</PrimaryButton>{form.recentlySuccessful && <span className="text-sm font-semibold text-brand-700">Dados salvos.</span>}</div></form></section>;
}
