import ContinueLearningCard from '@/Components/ContinueLearningCard';
import CourseRailCard from '@/Components/CourseRailCard';
import OfferCard from '@/Components/OfferCard';
import StudentLayout from '@/Layouts/StudentLayout';
import { Head, Link, usePage } from '@inertiajs/react';
import { PageProps } from '@/types';
import { ReactNode } from 'react';

type Course = { id: number; title: string; slug: string; thumbnailPath?: string | null; category?: string | null; level?: string | null; progress: number; lessonCount: number; enrolled?: boolean };
type Offer = { id: number; programName: string; priceCents: number; expiresAt?: string | null; courseCount: number };
type Props = { courses: Course[]; offers: Offer[]; continueLearning?: { lessonId: number; lessonTitle: string; moduleTitle: string; courseTitle: string; courseSlug: string; thumbnailPath?: string | null; progress: number } | null };

function Rail({ title, href, children }: { title: string; href?: string; children: ReactNode }) {
    return <section className="mt-14 sm:mt-20"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Sua biblioteca</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl">{title}</h2></div>{href && <Link className="mb-1 shrink-0 text-sm font-bold text-white/70 transition hover:text-[#d9b5ff]" href={href}>Ver todos <span aria-hidden className="ml-1 text-[#c28aff]">→</span></Link>}</div>{children}</section>;
}

export default function Dashboard({ courses, offers, continueLearning }: Props) {
    const { auth } = usePage<PageProps>().props;
    const firstName = auth.user.name.split(' ')[0];

    return <StudentLayout><Head title="Minha aprendizagem" />
        <section className="student-hero relative isolate overflow-hidden rounded-[1.35rem] border border-white/[0.11] bg-[#131018] px-6 py-10 shadow-[0_28px_80px_rgba(0,0,0,.32)] sm:px-10 sm:py-14 lg:min-h-[440px] lg:px-14 lg:py-16"><div aria-hidden className="absolute inset-0 bg-[url('/brand/student-hero-operations.png')] bg-cover bg-[67%_center] opacity-55 lg:bg-right" /><div aria-hidden className="absolute inset-0 bg-[linear-gradient(90deg,#100d15_0%,rgba(16,13,21,.96)_35%,rgba(16,13,21,.52)_60%,rgba(16,13,21,.12)_100%)]" /><div aria-hidden className="absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-[#100d15] to-transparent" /><div className="relative max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.19em] text-[#d3a5ff]">Olá, {firstName}</p><h1 className="mt-4 max-w-lg text-4xl font-black leading-[.98] tracking-[-0.06em] text-white sm:text-6xl">Sua próxima evolução começa aqui.</h1><p className="mt-5 max-w-md text-base leading-7 text-white/72 sm:text-lg">Conteúdo prático para elevar a sua operação e criar experiências que ficam.</p><div className="mt-8 flex flex-wrap gap-3">{continueLearning ? <Link className="asex-gradient inline-flex min-h-12 items-center rounded-lg px-6 py-3 text-sm font-bold text-white transition hover:brightness-110" href={`/lessons/${continueLearning.lessonId}`}>Continuar estudando <span aria-hidden className="ml-2">→</span></Link> : <Link className="asex-gradient inline-flex min-h-12 items-center rounded-lg px-6 py-3 text-sm font-bold text-white transition hover:brightness-110" href="/courses">Explorar programas <span aria-hidden className="ml-2">→</span></Link>}{offers.length > 0 && <Link className="inline-flex min-h-12 items-center rounded-lg border border-white/25 bg-black/15 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/[0.1]" href="/courses">Ver oferta especial</Link>}</div>{continueLearning && <p className="mt-8 text-sm font-semibold text-white/60"><span className="text-[#d3a5ff]">Em andamento</span><span aria-hidden className="mx-2 text-white/25">•</span>{continueLearning.courseTitle}</p>}</div></section>
        {offers.length > 0 && <section className="mt-12 sm:mt-16"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Programa selecionado</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl">Uma nova etapa para você.</h2></div><Link className="mb-1 shrink-0 text-sm font-bold text-white/70 transition hover:text-[#d9b5ff]" href="/courses">Ver todos <span aria-hidden className="ml-1 text-[#c28aff]">→</span></Link></div><div className="max-w-4xl"><OfferCard offer={offers[0]} /></div></section>}
        {continueLearning && <section className="mt-14 sm:mt-20"><div className="mb-6"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Agora</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl">Continue de onde parou.</h2></div><ContinueLearningCard {...continueLearning} /></section>}
        {courses.length > 0 && <Rail href="/my-courses" title="Meus cursos"><div className="student-scrollbar -mx-5 flex snap-x snap-mandatory gap-4 overflow-x-auto px-5 pb-2 sm:-mx-8 sm:px-8 lg:-mx-0 lg:px-0">{courses.map((course) => <div className="snap-start" key={course.id}><CourseRailCard course={course} /></div>)}</div></Rail>}
        {!courses.length && !offers.length && <section className="mt-14 max-w-2xl rounded-[1.35rem] border border-dashed border-white/15 bg-white/[0.025] px-6 py-12 sm:mt-20 sm:px-10"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#c28aff]">Sua biblioteca</p><h2 className="mt-3 text-3xl font-black tracking-[-0.04em] text-white">Pronta para o seu próximo capítulo.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-white/60 sm:text-base">Quando um programa for preparado para você, ele aparecerá aqui para pagamento e acesso.</p><Link className="mt-7 inline-flex text-sm font-bold text-[#d3a5ff] transition hover:text-white" href="/courses">Ver programas disponíveis <span aria-hidden className="ml-1">→</span></Link></section>}
    </StudentLayout>;
}
