import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';

type Sale = { id: number; student: { name: string; email: string }; programName: string; amountCents: number; status: string; createdAt: string; paidAt?: string | null };
const filters = ['ALL', 'PENDING', 'PAID', 'FAILED', 'CANCELLED'];
const price = (cents: number): string => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);

export default function Index({ sales, status }: { sales: Sale[]; status: string }) {
    return <AdminLayout><Head title="Vendas" /><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="admin-eyebrow">Comercial</p><h1 className="admin-page-title">Vendas</h1><p className="admin-page-subtitle">Pedidos reais, sem métricas artificiais.</p></div><Link className="admin-primary-button" href="/admin/offers/create">Criar oferta</Link></div><div aria-label="Filtrar vendas" className="mt-7 flex flex-wrap gap-2">{filters.map((filter) => <button className={`rounded-full border px-4 py-2 text-sm font-bold ${status === filter ? 'border-[#c28aff] bg-[#6429aa]/35 text-white' : 'border-white/15 text-[#C9C0D4]'}`} key={filter} onClick={() => router.get('/admin/sales', filter === 'ALL' ? {} : { status: filter })} type="button">{filter === 'ALL' ? 'Todos' : filter}</button>)}</div><section className="admin-panel mt-6 overflow-hidden">{sales.length ? <div className="overflow-x-auto"><table className="admin-table min-w-[850px]"><thead><tr><th>Aluno</th><th>Programa</th><th>Valor</th><th>Status</th><th>Data</th><th className="text-right">Detalhe</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id}><td><strong className="block text-[#F4F1FA]">{sale.student.name}</strong><small className="text-[#AAA0B9]">{sale.student.email}</small></td><td>{sale.programName}</td><td>{price(sale.amountCents)}</td><td>{sale.status}</td><td>{new Date(sale.createdAt).toLocaleDateString('pt-BR')}</td><td className="text-right"><Link className="admin-secondary-link" href={`/admin/sales/${sale.id}`}>Abrir</Link></td></tr>)}</tbody></table></div> : <div className="admin-empty-state py-16"><p>Nenhuma venda neste filtro.</p></div>}</section></AdminLayout>;
}
