import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link } from '@inertiajs/react';

type Sale = { id: number; orderNsu: string; programName: string; amountCents: number; status: string; student: { name: string; email: string }; courses: { id: number; title: string }[]; transactionId?: string | null; createdAt: string; paidAt?: string | null };
const price = (cents: number): string => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);

export default function Show({ sale }: { sale: Sale }) {
    return <AdminLayout><Head title="Detalhe da venda" /><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="admin-eyebrow">Venda #{sale.id}</p><h1 className="admin-page-title">{sale.programName}</h1><p className="admin-page-subtitle">Pedido e snapshot comercial.</p></div><Link className="admin-secondary-link" href="/admin/sales">Voltar para vendas</Link></div><section className="admin-panel mt-8 max-w-3xl p-6 sm:p-8"><dl className="grid gap-6 sm:grid-cols-2"><div><dt>Aluno</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{sale.student.name}<small className="mt-1 block font-normal text-[#AAA0B9]">{sale.student.email}</small></dd></div><div><dt>Valor</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{price(sale.amountCents)}</dd></div><div><dt>Status</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{sale.status}</dd></div><div><dt>Criada em</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{new Date(sale.createdAt).toLocaleString('pt-BR')}</dd></div><div><dt>order_nsu</dt><dd className="mt-1 break-all font-mono text-sm text-[#F4F1FA]">{sale.orderNsu}</dd></div><div><dt>transaction_nsu</dt><dd className="mt-1 break-all font-mono text-sm text-[#F4F1FA]">{sale.transactionId ?? '—'}</dd></div></dl><section className="mt-8 border-t border-white/10 pt-6"><h2 className="font-bold text-[#F4F1FA]">Cursos do snapshot</h2><ul className="mt-3 space-y-2 text-sm text-[#C9C0D4]">{sale.courses.map((course) => <li key={course.id}>✓ {course.title}</li>)}</ul></section></section></AdminLayout>;
}
