import AdminLayout from '@/Layouts/AdminLayout';
import { FormEvent } from 'react';
import { Head, router, useForm } from '@inertiajs/react';

type Lesson = { id: number; title: string; position: number; video_provider: 'youtube' | 'panda'; video_id?: string | null; video_url?: string | null; duration_seconds?: number | null; is_preview: boolean; description?: string | null; };
type Module = { id: number; title: string; position: number; lessons: Lesson[]; };
type Course = { id: number; title: string; slug: string; description?: string | null; status: 'DRAFT' | 'PUBLISHED'; modules: Module[]; };

function ModuleCreator({ course, nextPosition }: { course: Course; nextPosition: number }) {
    const form = useForm({ title: '', position: nextPosition });
    const submit = (event: FormEvent) => { event.preventDefault(); form.post(`/admin/courses/${course.id}/modules`, { preserveScroll: true, onSuccess: () => form.reset('title') }); };
    return <form onSubmit={submit} className="mt-4 flex flex-wrap gap-3"><input className="rounded-lg border-slate-300 text-sm" placeholder="Novo módulo" value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} required /><input className="w-20 rounded-lg border-slate-300 text-sm" type="number" min="1" value={form.data.position} onChange={(e) => form.setData('position', Number(e.target.value))} /><button className="rounded-lg border border-indigo-200 px-3 py-2 text-sm font-bold text-indigo-700" disabled={form.processing}>Adicionar módulo</button></form>;
}

function LessonCreator({ module, nextPosition }: { module: Module; nextPosition: number }) {
    const form = useForm({ title: '', description: '', video_provider: 'youtube' as 'youtube' | 'panda', video_id: '', video_url: '', duration_seconds: 0, position: nextPosition, is_preview: false });
    const submit = (event: FormEvent) => { event.preventDefault(); form.post(`/admin/modules/${module.id}/lessons`, { preserveScroll: true, onSuccess: () => form.reset('title', 'description', 'video_id', 'video_url') }); };
    return <form onSubmit={submit} className="mt-3 grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-2"><input className="rounded-md border-slate-300 text-sm" placeholder="Título da aula" value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} required /><input className="rounded-md border-slate-300 text-sm" placeholder="ID do vídeo (YouTube/Panda)" value={form.data.video_id} onChange={(e) => form.setData('video_id', e.target.value)} required /><select className="rounded-md border-slate-300 text-sm" value={form.data.video_provider} onChange={(e) => form.setData('video_provider', e.target.value as 'youtube' | 'panda')}><option value="youtube">YouTube</option><option value="panda">Panda Video</option></select><div className="flex gap-2"><input className="w-20 rounded-md border-slate-300 text-sm" type="number" min="1" value={form.data.position} onChange={(e) => form.setData('position', Number(e.target.value))} /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={form.data.is_preview} onChange={(e) => form.setData('is_preview', e.target.checked)} />Prévia</label><button className="ml-auto text-sm font-bold text-indigo-700" disabled={form.processing}>Adicionar aula</button></div></form>;
}

function ModuleEditor({ module, course }: { module: Module; course: Course }) {
    const updateModule = () => { const title = prompt('Nome do módulo', module.title); if (title) router.put(`/admin/modules/${module.id}`, { title, position: module.position }, { preserveScroll: true }); };
    const deleteModule = () => { if (confirm(`Excluir módulo “${module.title}”?`)) router.delete(`/admin/modules/${module.id}`, { preserveScroll: true }); };
    const moveModule = (offset: number) => { const ids = course.modules.map((item) => item.id); const index = ids.indexOf(module.id); const target = index + offset; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; router.put(`/admin/courses/${course.id}/modules/reorder`, { module_ids: ids }, { preserveScroll: true }); };
    const moveLesson = (lesson: Lesson, offset: number) => { const ids = module.lessons.map((item) => item.id); const index = ids.indexOf(lesson.id); const target = index + offset; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; router.put(`/admin/modules/${module.id}/lessons/reorder`, { lesson_ids: ids }, { preserveScroll: true }); };
    const updateLesson = (lesson: Lesson) => { const title = prompt('Nome da aula', lesson.title); if (title) router.put(`/admin/lessons/${lesson.id}`, { ...lesson, title, is_preview: lesson.is_preview, video_provider: lesson.video_provider }, { preserveScroll: true }); };
    return <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold text-slate-900">{module.position}. {module.title}</p><p className="text-sm text-slate-500">{module.lessons.length} aulas</p></div><div className="flex gap-3"><button type="button" onClick={() => moveModule(-1)} className="text-sm font-semibold text-slate-700">↑</button><button type="button" onClick={() => moveModule(1)} className="text-sm font-semibold text-slate-700">↓</button><button type="button" onClick={updateModule} className="text-sm font-semibold text-indigo-700">Editar</button><button type="button" onClick={deleteModule} className="text-sm font-semibold text-rose-700">Excluir</button></div></div><ul className="mt-3 divide-y divide-slate-100">{module.lessons.map((lesson) => <li key={lesson.id} className="flex justify-between gap-3 py-2 text-sm"><span>{lesson.position}. {lesson.title}</span><div className="flex gap-3"><button type="button" onClick={() => moveLesson(lesson, -1)}>↑</button><button type="button" onClick={() => moveLesson(lesson, 1)}>↓</button><span className="text-slate-500">{lesson.video_provider}</span><button className="font-semibold text-indigo-700" type="button" onClick={() => updateLesson(lesson)}>Editar</button><button className="font-semibold text-rose-700" type="button" onClick={() => { if (confirm(`Excluir aula “${lesson.title}”?`)) router.delete(`/admin/lessons/${lesson.id}`, { preserveScroll: true }); }}>Excluir</button></div></li>)}</ul><LessonCreator module={module} nextPosition={module.lessons.length + 1} /></section>;
}

export default function Form({ course }: { course?: Course }) {
    const form = useForm({ title: course?.title ?? '', slug: course?.slug ?? '', description: course?.description ?? '', status: course?.status ?? 'DRAFT', thumbnail: null as File | null });
    const submit = (event: FormEvent) => { event.preventDefault(); if (course) form.put(`/admin/courses/${course.id}`, { forceFormData: true, preserveScroll: true }); else form.post('/admin/courses', { forceFormData: true }); };
    return <AdminLayout><Head title={course ? `Editar ${course.title}` : 'Novo curso'} /><h1 className="text-3xl font-black">{course ? 'Editar curso' : 'Novo curso'}</h1><form onSubmit={submit} className="mt-8 grid max-w-3xl gap-5 rounded-2xl border border-slate-200 bg-white p-6"><label className="grid gap-2 text-sm font-bold">Título<input className="rounded-lg border-slate-300" value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} required /></label><label className="grid gap-2 text-sm font-bold">Slug<input className="rounded-lg border-slate-300" value={form.data.slug} onChange={(e) => form.setData('slug', e.target.value)} required /></label><label className="grid gap-2 text-sm font-bold">Descrição<textarea className="rounded-lg border-slate-300" rows={4} value={form.data.description} onChange={(e) => form.setData('description', e.target.value)} /></label><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Status<select className="rounded-lg border-slate-300" value={form.data.status} onChange={(e) => form.setData('status', e.target.value as 'DRAFT' | 'PUBLISHED')}><option value="DRAFT">Rascunho</option><option value="PUBLISHED">Publicado</option></select></label><label className="grid gap-2 text-sm font-bold">Capa<input className="text-sm" type="file" accept="image/*" onChange={(e) => form.setData('thumbnail', e.target.files?.[0] ?? null)} /></label></div>{Object.values(form.errors).map((error) => <p key={error} className="text-sm text-rose-700">{error}</p>)}<button className="w-fit rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white" disabled={form.processing}>{course ? 'Salvar alterações' : 'Criar curso'}</button></form>{course && <section className="mt-10 max-w-3xl"><h2 className="text-2xl font-black">Estrutura do curso</h2><ModuleCreator course={course} nextPosition={course.modules.length + 1} /><div className="mt-5 space-y-4">{course.modules.map((module) => <ModuleEditor key={module.id} module={module} course={course} />)}</div></section>}</AdminLayout>;
}
