import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';

type Course = { id: number; title: string; slug: string; status: 'DRAFT' | 'PUBLISHED'; modules_count: number; lessons_count: number; enrollments_count: number; };

export default function Index({ courses }: { courses: Course[] }) {
    const remove = (course: Course) => { if (confirm(`Excluir “${course.title}”?`)) router.delete(`/admin/courses/${course.id}`); };
    return <AdminLayout><Head title="Administração de cursos" /><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Administração</p><h1 className="mt-2 text-3xl font-black">Cursos</h1></div><Link className="rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-800" href="/admin/courses/create">Novo curso</Link></div><div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-[1fr_auto_auto_auto_auto] gap-6 border-b border-slate-100 px-6 py-3 text-xs font-bold uppercase tracking-wider text-slate-500 md:grid"><span>Curso</span><span>Módulos</span><span>Aulas</span><span>Alunos</span><span>Ações</span></div>{courses.map((course) => <div key={course.id} className="grid gap-3 border-b border-slate-100 px-6 py-5 md:grid-cols-[1fr_auto_auto_auto_auto] md:items-center md:gap-6"><div><p className="font-bold text-slate-900">{course.title}</p><p className="mt-1 text-sm text-slate-500">{course.status === 'PUBLISHED' ? 'Publicado' : 'Rascunho'} · /{course.slug}</p></div><span className="text-sm text-slate-600">{course.modules_count}</span><span className="text-sm text-slate-600">{course.lessons_count}</span><Link className="text-sm font-semibold text-indigo-700 hover:text-indigo-900" href={`/admin/courses/${course.id}/students`}>{course.enrollments_count} alunos</Link><div className="flex gap-3 text-sm font-semibold"><Link className="text-indigo-700 hover:text-indigo-900" href={`/admin/courses/${course.id}/edit`}>Editar</Link><button className="text-rose-700 hover:text-rose-900" type="button" onClick={() => remove(course)}>Excluir</button></div></div>)}{!courses.length && <p className="p-8 text-center text-slate-600">Nenhum curso cadastrado.</p>}</div></AdminLayout>;
}
