import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { FormEvent, useMemo } from 'react';

type Student = { id: number; name: string; email: string };
type Program = { id: number; name: string; defaultPriceCents: number; courses: { id: number; title: string }[] };
const price = (cents: number): string => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);

export default function Create({ students, programs }: { students: Student[]; programs: Program[] }) {
    const form = useForm({ user_id: '', program_id: '', price_cents: 0, expires_at: '' });
    const selected = useMemo(() => programs.find((program) => program.id === Number(form.data.program_id)), [form.data.program_id, programs]);
    const selectProgram = (id: string): void => { const program = programs.find((item) => item.id === Number(id)); form.setData((data) => ({ ...data, program_id: id, price_cents: program?.defaultPriceCents ?? 0 })); };
    const submit = (event: FormEvent): void => { event.preventDefault(); form.post('/admin/offers'); };

    return <AdminLayout><Head title="Criar oferta" /><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="admin-eyebrow">Comercial</p><h1 className="admin-page-title">Criar oferta</h1><p className="admin-page-subtitle">Uma oferta é visível somente para o aluno selecionado.</p></div><Link className="admin-secondary-link" href="/admin/sales">Voltar para vendas</Link></div><form className="admin-panel mt-8 max-w-3xl p-6 sm:p-8" onSubmit={submit}><div className="grid gap-5 md:grid-cols-2"><label className="admin-field"><span>Aluno</span><select required value={form.data.user_id} onChange={(event) => form.setData('user_id', event.target.value)}><option value="">Selecionar aluno</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name} — {student.email}</option>)}</select><small>{form.errors.user_id}</small></label><label className="admin-field"><span>Programa</span><select required value={form.data.program_id} onChange={(event) => selectProgram(event.target.value)}><option value="">Selecionar programa</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select><small>{form.errors.program_id}</small></label><label className="admin-field"><span>Preço desta oferta (centavos)</span><input min="0" required type="number" value={form.data.price_cents} onChange={(event) => form.setData('price_cents', Number(event.target.value))} /><small>{price(form.data.price_cents)}. {form.errors.price_cents}</small></label><label className="admin-field"><span>Validade</span><input type="datetime-local" value={form.data.expires_at} onChange={(event) => form.setData('expires_at', event.target.value)} /><small>{form.errors.expires_at}</small></label></div>{selected && <section className="mt-7 rounded-xl border border-white/10 bg-white/[0.025] p-5"><p className="text-sm font-bold text-[#F4F1FA]">Cursos incluídos</p><ul className="mt-3 space-y-2 text-sm text-[#C9C0D4]">{selected.courses.map((course) => <li key={course.id}>✓ {course.title}</li>)}</ul></section>}<div className="mt-8 flex flex-wrap gap-3"><button className="admin-primary-button disabled:opacity-50" disabled={form.processing} type="submit">{form.processing ? 'Criando…' : 'Criar oferta'}</button><Link className="admin-secondary-link" href="/admin/sales">Cancelar</Link></div></form></AdminLayout>;
}
