import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';

type Offer = { id: number; programName: string; priceCents: number; status: string; expiresAt?: string | null; student: { name: string; email: string }; courses: { id: number; title: string }[]; checkoutUrl?: string | null };
const price = (cents: number): string => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);

export default function Show({ offer }: { offer: Offer }) {
    const cancel = (): void => router.delete(`/admin/offers/${offer.id}`);
    const copy = async (): Promise<void> => { if (offer.checkoutUrl) await navigator.clipboard.writeText(offer.checkoutUrl); };
    return <AdminLayout><Head title="Oferta" /><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="admin-eyebrow">Oferta criada</p><h1 className="admin-page-title">Disponível na conta do aluno</h1><p className="admin-page-subtitle">{offer.programName} já está disponível para {offer.student.name} realizar o pagamento.</p></div><Link className="admin-secondary-link" href="/admin/sales">Ver vendas</Link></div><section className="admin-panel mt-8 max-w-3xl p-6 sm:p-8"><div className="mb-8 rounded-xl border border-[#9347DD]/25 bg-[#6429AA]/10 px-4 py-3 text-sm text-[#E9D5FF]">A oferta já aparece na área do aluno. O acesso aos cursos continua condicionado à confirmação do pagamento.</div><dl className="grid gap-6 sm:grid-cols-2"><div><dt>Aluno</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{offer.student.name}<small className="mt-1 block font-normal text-[#AAA0B9]">{offer.student.email}</small></dd></div><div><dt>Valor</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{price(offer.priceCents)}</dd></div><div><dt>Status</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{offer.status}</dd></div><div><dt>Validade</dt><dd className="mt-1 font-bold text-[#F4F1FA]">{offer.expiresAt ? new Date(offer.expiresAt).toLocaleString('pt-BR') : 'Sem prazo'}</dd></div></dl><section className="mt-8 border-t border-white/10 pt-6"><h2 className="font-bold text-[#F4F1FA]">Cursos incluídos</h2><ul className="mt-3 space-y-2 text-sm text-[#C9C0D4]">{offer.courses.map((course) => <li key={course.id}>✓ {course.title}</li>)}</ul></section><div className="mt-8 flex flex-wrap gap-3">{offer.checkoutUrl && <><a className="admin-primary-button" href={offer.checkoutUrl} rel="noreferrer" target="_blank">Abrir checkout</a><button className="admin-secondary-link" onClick={() => void copy()} type="button">Copiar checkout</button></>} {offer.status === 'PENDING' && <button className="admin-danger-link" onClick={cancel} type="button">Cancelar oferta</button>}</div></section></AdminLayout>;
}
